/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Decode a buffer to a string with a given encoding label */
export declare function decode(input: Uint8Array, encodingLabel: string): string

/** Encode a string to a buffer with a given encoding label */
export declare function encode(input: string, encodingLabel: string): Buffer

/**
 * Encode a buffer from one encoding label to another
 *
 * This function performs transcoding with minimal allocations by using Cow<str>
 * from encoding_rs. While encoding_rs only supports UTF-8 as intermediate format,
 * we avoid unnecessary String allocations when possible.
 */
export declare function encodeWithBuffer(input: Uint8Array, fromEncodingLabel: string, toEncodingLabel: string): Buffer
