/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Decode a buffer to a string with a given charset */
export declare function decode(input: Buffer, charset: string): string

/** Encode a string to a buffer with a given charset */
export declare function encode(input: string, charset: string): Buffer

/**
 * Encode a buffer from one charset to another
 *
 * This function performs transcoding with minimal allocations by using Cow<str>
 * from encoding_rs. While encoding_rs only supports UTF-8 as intermediate format,
 * we avoid unnecessary String allocations when possible.
 */
export declare function encodeWithBuffer(input: Buffer, fromCharset: string, toCharset: string): Buffer
