/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function decode(input: Buffer, charset: string): string

export declare function encode(input: string, charset: string): Buffer

export declare function encodeWithBuffer(input: Buffer, fromCharset: string, toCharset: string): Buffer
