import { defineConfig } from 'tsup'

export default defineConfig([
  // CommonJS build
  {
    entry: ['wrapper.ts'],
    format: 'cjs',
    outDir: '.',
    outExtension: () => ({ js: '.js' }),
    dts: {
      entry: 'wrapper.ts',
    },
    clean: false,
    shims: true,
    banner: {
      js: `/**
 * This file is generated from wrapper.ts
 * Do not edit this file directly. Edit wrapper.ts instead.
 */`
    }
  },
  // ESM build
  {
    entry: ['wrapper.ts'],
    format: 'esm',
    outDir: '.',
    outExtension: () => ({ js: '.mjs' }),
    dts: false, // We only need one .d.ts file
    clean: false,
    shims: true,
    banner: {
      js: `/**
 * This file is generated from wrapper.ts
 * Do not edit this file directly. Edit wrapper.ts instead.
 */`
    }
  }
])